server:
  port: 8001
spring:
  application:
    name: spring-boot-10-client
spring-boot-server:
  name: myfirst-springmvc-datajpa
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/