server:
  port: 8001
spring:
  application:
    name: spring-boot-10-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
countryRegionService:
  service-name: myfirst-springmvc-datajpa
  username: user
  password: password
